accounts:
  - name: user1
    coins: ["10000000000000000CST"]
  - name: user2
    coins: ["10000000000000000CST"]
validator:
  name: user1
  staked: "1000000000000CST"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: user2
  coins: ["100000000CST"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "CST"
